services:
  redis:
    image: 'redis'
    container_name: redis
    ports:
      - "6379:6379"

  producer:
    build: ./producer
    container_name: taskqueue-producer
    ports:
      - "8080:8080"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis

  worker:
    build: ./worker
    container_name: taskqueue-worker
    ports:
      - "8081:8081"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis

  postgres:
    image: postgres:15-alpine
    container_name: taskqueue-postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: task_history
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data